### ISSUE TITLE
Doesn't support Intel Gigabit Ethernet (igc module)

### ISSUE THREAD

**Issue by TheUtopian** [porteux/porteux#12]
Hi, My motherboard has the intel gigabit ethernet adapter (**i225-v**), it needs igc module to be enabled.
I had the same issue with Porteus 5, but someone compiled kernel module for me. I wanted to compile Porteux kernel myself but I don't understand where I need to add igc module to be included in the **createModule.sh**. Could you help?
Thanks in advance.

**Comment by porteux** [comment]
@TheUtopian, I believe you need to edit 64bit.config and change `# CONFIG_IGC is not set` to `CONFIG_IGC=m`.

Let me know if this fixes your issue so I can update the config file for the next release :)

**Comment by TheUtopian** [comment]
Actually, I have seen that file and line, but at the begging it says: this file is autogenerated, don't change it so I ignore it. I'll try, thanks.

**Comment by TheUtopian** [comment]
@porteux , it took about 2 hours and the script downloaded 6.2.1 kernel not 6.3.3 but anyway it **WORKS**! Thank you for help.

**Comment by porteux** [comment]
I'm glad it worked! I'm including this new configuration in the kernel config file so in the next PorteuX release it will work out of the box for you :)

Regarding the kernel version, I forgot to update the KERNELVERSION variable because I was compiling passing the kernel version parameter: `./createModule.sh 6.3.3`. Gonna fix that too. Thanks!
