### ISSUE TITLE
Non critical issue - "jq" utility dosen't work (Gnome stable/current)

### ISSUE THREAD

**Issue by TheUtopian** [porteux/porteux#15]
Gnome modules include **jq** utility which requires **oniguruma** library but It's available only for Slackware 14.2 (https://slackbuilds.org/repository/14.2/development/oniguruma/) so it's not included by default but I tested it and it works well.

P.S
This is very useful utility, it'd great if you will include it into "extra" module.
If you'll want to, I made a module for myself with the library included:
[jq-1.6-x86_64.tar.gz] (https://github.com/porteux/porteux/files/11582657/jq-1.6-x86_64.tar.gz).

**Comment by porteux** [comment]
@TheUtopian, thanks for checking this. Actually, **jq** is not even necessary in GNOME. I'm gonna remove it from the module in the next release.

The idea behind PorteuX is to include only the basic packages for the system to work properly. Anything else should be added by the user, otherwise we'll end up having a bloated system.

**Comment by TheUtopian** [comment]
@porteux, that's reasonable. I'll keep it for myself then).
