### ISSUE TITLE
changes=EXIT:/

### ISSUE THREAD

**Issue by jobidon** [porteux/porteux#36]
I'm investigating the cause of a slowdown during boot on a desktop with Porteux v1.2. The issue was *not* present when v1.1 was initially installed, and it is unclear when it started to occur, but the issue is still present after upgrading to v1.2.

If I boot the system with the parameter `changes=EXIT:/`, the system stay idle during boot for ~1330 seconds (21+ minutes!) before resuming the boot sequence and booting normally. The situation persists even if I specify `nomagic norootcopy 3`. It hangs *before* loading the base xzm modules and the live filesystem. It basically hangs immediately after displaying the cyan line indicating that the changes will be saved only at reboot/shutdown. After the 20+ min. wait, the first log entry in the system log is a reference to aufs.

If instead I change the cheatcode to `changes=/` (without the `EXIT:`) it boots immediately without delay and configuration changes persist after a reboot with this configuration as well. So obviously, waiting to save changes at shutdown causes the 20 minutes wait.

Any idea what could be going on? How can I troubleshoot this to determine what causes this? From what I could gather, adding the `debug` option does not generate any additional helpful troubleshooting information in this case.

thanks for your help!

**Comment by jobidon** [comment]
thanks for the quick reply!

1. fsck reports that there is a mismatch between the bootsectors, but other than that, the partition is all clean. I rebooted with `changes=EXIT:/` and the problem remains
2. Actually, the problem was initially noticed in 1.1. I upgraded to 1.2 to see if it would resolve itself but it didn't. So the problem occurs both in 1.1 and 1.2
3. n/a
4. When the system was initially installed (with 1.1) the `EXIT:` parameter was specified and it worked fine: no delay at boot, and saving only occurred at shutdown/reboot, as expected. After a month or so of daily use, the problem surfaced (but the exact trigger is unknown). And if I wait the 1330 seconds and let it boot, everything works fine, even the save at reboot. Note that there are no delays when *saving* the changes, the delay only occurs while booting.

is there a way to add traces when the kernel processes that parameter to determine more precisely when this occurs? Perhaps a special kernel with kdb?

**Comment by porteux** [comment]
1. OK
2. It would be great if you could go back until you find which version works. As I said, we need a reliable way to replicate the issue. Speaking of that, I tried to replicate using PorteuX 1.2 current + LXQt, and I couldn't; using `changes=EXIT:` boots normally
3. same as above: once you find a version that works, try to mix its `initrd.zst` with PorteuX 1.2 and see how it goes
4. I see. Well, it seems the problem is not related to any specific version of PorteuX. So most likely your session is corrupted somehow or unit storage unit is faulty. Is it possible to start a new session just to make sure? If it still doesn't work, could you try a fresh PorteuX in another storage unit?

I don't think this is related to the kernel. Do you mind posting a picture of the screen where it gets frozen?

**Comment by jobidon** [comment]
Sorry for the delay: I don't have access to this PC all the time

I tried booting with different versions of initrd and it does NOT resolve the issue. I even tried changing the default login name to another account on that PC and the problem remains.
I noticed that the `changes/` directory is over 11GB in size, mainly due to a huge `.cache` directory for a specific user. Deleting that folder did not help the issue. Could the issue be caused by a symlink to a remote nfs folder that is not yet available at that point during boot?

[Boot image](https://i.postimg.cc/W3ndTDn9/IMG-20240504-120948-702.jpg)

**Comment by porteux** [comment]
1. Have you tried to revert PorteuX to a version that works for you?
2. Have you tried a new session from scratch?
3. Have you tried another storage unit?

> Could the issue be caused by a symlink to a remote nfs folder that is not yet available at that point during boot?

Maybe. It's worth trying.

**Comment by porteux** [comment]
BTW, this a testing `initrd.zst` for you to test. Please, don't ignore the questions from my last post.

[initrd.zst.zip](https://github.com/porteux/porteux/files/15226726/initrd.zst.zip)

Of course, remember to extract the zip content.

**Comment by jobidon** [comment]
Interestingly, when I load the test initrd file you just sent (version 2023 09 27) along with Porteux v1.2, the problem does *not* occur: Even with the `EXIT:/` cheatcode, there is no delay at boot.
I have not tried with a different storage unit nor a new session from scratch, but this new initrd appears to resolve the problem.
I was looking at the content of initrd to see the differences. apparently cryptsetup was added along with an update to exfatfsck. Do you think either could cause the delays?

**Comment by TheUtopian** [comment]
Hello @jobidon 

> I was looking at the content of initrd to see the differences. apparently cryptsetup was added along with an update to exfatfsck. Do you think either could cause the delays?
No it's not related to cryptsetup or exfatfsck. We accidentally sent you a new initrd.

The delay occurred because we run `find` command for "changes" directory in init script.
I think it happens either because you have very large "changes" dir. or because you've mounted some slow device in "changes".

I modified initrd a little bit more. If you can check it, please let me know if it fixes the issue for you, so we can update initrd in repository.

[initrd.zst.zip](https://github.com/porteux/porteux/files/15239427/initrd.zst.zip)

It's also possible that you've a lot of deleted files in "changes" dir. You can check it by running:
`find /mnt/live/memory/changes -name ".wh.*" | wc --lines`

**Comment by jobidon** [comment]
@TheUtopian : thanks for the quick update!
Unfortunately when I boot with the new initrd.zst file you sent, the boot process is very long. So for now, I reverted back to the one @porteux uploaded.
I noticed a few things:
1. the file `/etc/initrd.ver` has not been updated. Perhaps it would be easier to identify the updated version if it had the current date, and if it were displayed during the boot process (`Currently using initrd version xxxx`)
2. There are over 12GB of files in the `changes/` folder. Many of them are files marked for deletion (`.wh.*`). In fact, the `.cache` folder under the chromium-ungoogled subfolder has over 400,000 files! I have manually deleted the `.cache` folder and there are now 'only' 22K files marked for deletion: this introduces only a small delay in the boot process (~20 seconds). That's probably why the `-maxdepth 2` option of the find command in the first test initrd speeds things up. I will manually delete those files to clear this up.
3. I assumed the files marked for deletion would indeed be deleted at the next reboot, but apparently they aren't. Is there a way to manually for a sync and delete those entries from the `changes/` folder?
4. Finally, is there a way to exclude certain folders from the sync process? Perhaps folders like `Trash`, `RecentDocuments`, `.cache`, etc could be specified in a configuration file to prevent those files from being considered.

**Comment by TheUtopian** [comment]
Thank you for report!

1. You're right, I forgot to update that file. Displaying initrd version is not a bad idea, thanks, We'll disccuss about it.

3. We don't remove actual files because they are in .xzm modules and modules are readonly, We need `.wh.*` files to exclude them from the virtual filesystem. You run `find /mnt/live/memory/changes -name ".wh.*" | xargs rm` to remove all of those files.

4. You can exclude directroies from syncing in the file `/etc/changes-exit.conf`, just add the directory with exclamation mark, like `!/home/guest/.cache`

**Comment by jobidon** [comment]
Thanks for the suggestions. Now that the files are removed and the cache folder is ignored, the problem appears to be resolved: the system now boots up quickly, as expected.
