### ISSUE TITLE
Cannot boot from USB Stick anymore

### ISSUE THREAD

**Issue by eGit** [porteux/porteux#38]
Hello,

I followed the instructions on how to install PorteuX. I copied the files on an USB Stick. Then I booted into PorteuX using the UEFI Boot manager at startup.
I then created a Fat32 EFI partition and an ext4 partition and copied the files and executed the linux-install.sh

Everything worked great.

I now wanted to test a different DE. I created an USB Stick again, extracting a different ISO. I select the correct USB Stick in the UEFI Boot manager. But then I boots from the PorteuX installed on the harddisk and not my USB Stick PorteuX.

My guess is, that it sees:
/boot/syslinux/vmlinuz
/boot/syslinux/initrd.zst

exist on the laptop harddisk and somehow boots those instead of the versions on my USB Stick. Any idea how to prevent this?

**Comment by porteux** [comment]
If you just want to try a different desktop environment (DE), the easiest solution would be renaming your current DE suffix to `.xzm_` in `porteux/base`, copying the new DE to the same folder and rebooting.

If you want to keep 2 installations of PorteuX, make sure you have the latest version and do what you did except that now you have to make sure you run `boot/porteux-installer-for-linux.run`, since this application will make sure you have a unique ID of your media storage to look for during reboot.

Let me know if this fixes your issue.

**Comment by eGit** [comment]
I know about the renaming but I want a separate USB I can boot from using a completely separate PorteuX. But my Laptop always boots from the PorteuX installed on the harddisk.

How do I install PorteuX on the USB Stick? My Laptop has UEFI. So far, I created an EFI Fat32 partition and an ext4 partition on the USB Stick and copied the PorteuX data manually to the partitions. I never executed boot/porteux-installer-for-linux.run

**Comment by porteux** [comment]
> How do I install PorteuX on the USB Stick? My Laptop has UEFI. So far, I created an EFI Fat32 partition and an ext4 partition on the USB Stick and copied the PorteuX data manually to the partitions. I never executed boot/porteux-installer-for-linux.run

As I said, I recommend running `boot/porteux-installer-for-linux.run` because it injects the media storage unique ID into initrd, and that will be used during boot time to identify PorteuX partition. This is the easiest and most reliable solution for your case.

Another option would be using `from=` cheatcode. For more information, take a look at `boot/docs/cheatcodes.txt`

**Comment by eGit** [comment]
Thanks!
Btw, the PorteuX on the laptop harddisk was installed manually as described above. No installer.

**Comment by porteux** [comment]
Have you managed to fix your issue? Can we close this?

**Comment by eGit** [comment]
I installed PorteuX on my USB Stick following these instructions: http://www.porteus.org/tutorials/37-installing/114-official-porteus-installation-guide-v-10.html#USB-linux

It included the initrd according to the output in the console. My Laptop bios is picky though. If I select the USB Stick from the Boot Manager (UEFI UI) it tells me:

`Booting from 'USB: USB DISK Pro ' failed: verify it contains a 64-bit UEFI OS.`

It seems it expects an EFI/ESP Fat32 Partition to do all the booting.

**Comment by porteux** [comment]
I recommend reading PorteuX documentation instead. It's in `/boot/docs/install.txt`.

You should create a FAT32 partition and copy `/boot` and `/EFI` folders to it. In the second partition (btrfs, ext, FAT, NTFS or xfs) you put `/porteux` folder. After that you should run `/boot/porteux-installer-for-linux.run` and everything should work.

I'm closing this. If you find issues, please let us know.

Thanks!
