### ISSUE TITLE
Add support for Ventoy (UEFI X64 boot file)

### ISSUE THREAD

**Issue by hpigula** [porteux/porteux#40]
Hi I just tried to boot PorteuX via latest Ventoy but got either just aan Underscore "_" when choosing Normal Boot mode in Grub Boot Mode it shows  there is a file missing for UEFI X64 Boot and the info that it does not support UEFI X64 Boot.
Could you please add that support?

**Comment by porteux** [comment]
Ventoy needs to add support to PorteuX. I already [requested it](https://github.com/ventoy/Ventoy/issues/2722), but it seems they ignored. If you want to bump this issue in their Github page, it might help.

In the meantime, what should work is copying `/boot/syslinux/porteux.cfg` to `/boot/syslinux/porteus.cfg` ([source](https://forum.porteus.org/viewtopic.php?p=97926#p97926)), since Ventoy has added support to Porteus a long time ago.

Let me know if this works for you.

**Comment by hpigula** [comment]
Good to know have a nice day/weekend :)

W dniu pt., 30 sie 2024 o 14:17 PorteuX ***@***.***>
napisał(a):

**Comment by porteux** [comment]
After some research, we decided to not progress with this.

To fix this issue we have 2 options, and none of them seem ideal:

1. continue to use Syslinux, but then having to replicate `/boot/syslinux` folder content into a .img file
2. drop Syslinux in favor to GRUB

Because booting ISOs via EFI is something very specific and uncommon, for now we're keeping things the way they are. For those who really want to try PorteuX via ISO boot, either use legacy mode or Ventoy (fix [here](https://github.com/ventoy/Ventoy/issues/2722#issuecomment-2505005578)).
