### ISSUE TITLE
Support Core2Duo w. GMA 950 or X3100

### ISSUE THREAD

**Issue by ebbi2017** [porteux/porteux#45]
Hallo,

I've installed PorteuX 0.9 on an HP 2510p laptop w/ U7600 CPU, 4 GB RAM, SSD, which runs super fast.
I can even upgrade the browser, but not the system itself.
Now I'd thought to upgrade/reinstall PorteuX 1.7, which failed and tried all newer iso files booted from within Ventoy.
(Ventoy + Porteus 5.0.1 newest works, startx works.)
Ventoy + PorteuX 0.9 works, startx works.
Ventoy + PorteuX 1.0, 1.1, 1.2, 1,3, 1.4, 1.5, 1.6, 1.7 all boot into console, but startx doesn't work anymore. It just goes back to terminal.
When trying normal boot w/o console, the screen goes black and flickers every some second, showing the console part.

Do you have some Core2Duo laptop w/ GMA950/X3100 iGPU to test it?

On another i5 Dell desktop w/ HD4000 iGPU it boots fine this way, but not on the Core2Duo laptop.

Thx in advance

**Comment by porteux** [comment]
Starting with PorteuX 1.0, we only provide support for `x86-64-v2` CPUs, which means it needs to have SSE4 instruction, something Core2Duo doesn't have. This decision was made because PorteuX is focused on performance, and we don't have the resources to compile for multiple architectures. I'm sorry.

If you want to upgrade, the only option is to compile PorteuX yourself. To do this, you will need to modify the  `ARCHITECTURELEVEL` variable to `x86-64` (instead of `x86-64-v2`) in the `builder-utils/setflags.sh` script file. Instructions for building PorteuX can be found on the project's GitHub page (tip: you can easily build it using your i5 machine).

I'm closing this issue, but if you have any other question, feel free to ask. :)
