### ISSUE TITLE
Doesn't support x64 (U)EFI (repeat important issue)

### ISSUE THREAD

**Issue by ZX-Commodore-ST** [porteux/porteux#46]
https://github.com/porteux/porteux/issues/29 - Don't understand why it was closed. Iso doesn't boot on UEFI PCs. It's a serious issue that is overlooked by many minor distros like Porteus, Porteux, Slax, Slitaz, Tiny Core Linux etc. Many PCs don't have BIOS or CSM boot option at all! They need UEFI boot to work. Reading all other threads I think you already know it doesn't boot. To say that it works it has to be able to boot from CD/DVD without any additional tool like Ventoy, YUMI, Rufus, Balena Etcher etc. Fast way to check it is to use Qemu or Virtualbox EFI boot from iso. 

On a side note I was able to fix Ventoy UEFI booting with a solution (add /boot/grub/grub.cfg file) from here: https://forum.porteus.org/viewtopic.php?p=87922#p87922

It looks that Slitaz just recently fixed UEFI booting: https://people.slitaz.org/~shann/slitaz-current64-stuff/ Maybe it's time to leave syslinux for grub?

**Comment by porteux** [comment]
There's already [an issue open](https://github.com/porteux/porteux/issues/40) for this.

Anyway, what exactly are you trying to achieve?

PorteuX can definitely boot using EFI -- that's what most users are doing, including me :)

What it doesn't support at the moment is booting the ISO via EFI, but that's a very specific scenario that apart from Ventoy (which you already found a solution) and VMs (which usually support legacy boot), I don't see any reason to use, especially because the ISOs are read-only, and that's not the preferred way of using PorteuX.

**Comment by ZX-Commodore-ST** [comment]
Many users don't know much about advanced boot options like Ventoy. Believe it or not some of them will still try to use real CD/DVD drive because that's what iso file is for. Many first time users are like that. Anyway, they will give exactly one try for this new distro they never used before and if it doesn't even boot on their PC they will run away without troubleshooting why it didn't work. Me and [ebbi2017](https://github.com/ebbi2017) took our time to post feedback about this. What I'm trying to achieve? Nothing, I have nothing to gain, It's up to you. I'm not a Linux person but I wish you lot of success as I find your distro useful for my own homemade kiosk type of install. BTW I follow Porteus for more than 10 years and I never use changes.dat.

Not so long ago Distrowatch had a review of PorteuX. Jesse Smith gave it thumbs up but still pointed out few shortcomings. He wasn't able to install custom software. What did he try to achieve? It's up to you what you do with feedback.

**Comment by porteux** [comment]
I appreciate your time reporting the issue and the willing to help.

Maybe you're missing the point that PorteuX already supports boot via CD/DVD/USB/HDD/SSD/whatever. Just follow the [install documentation](https://github.com/porteux/porteux/blob/main/boot/boot/docs/install.txt). It's super simple. Tip: you have to copy the ISO **content**, not the ISO itself.

If the user wants to use Etcher or Rufus, it's also going to work out of the box, but the storage unit will be read-only, and that's probably not what they want. That's why it's not recommended.

I see no reason to boot the actual ISO (especially if not using Ventoy). If you can give me some examples, that would be helpful.

Thanks!

**Comment by porteux** [comment]
Closing this. See more [here](https://github.com/porteux/porteux/issues/40#issuecomment-2508694573).

**Comment by ZX-Commodore-ST** [comment]
Second time you closed issue as "completed" instead of leaving it alone as a known bug or closing it as "not planned". This is far from an appreciation for feedback. It's just a different way of saying GFY.

PorteuX Iso is not compatible with UEFI standard. All other serious distros release UEFI capable isos. Even minor ones like Slitaz start to see reasoning behind it. If you don't understand why they do, ask them. It's not my job. But don't pretend it's not an issue as people are asking in many places. If they ask, they have a reason. PorteuX UEFI support out of the box is broken. That's a fact.

I had other feedback about AMD hardware but I won't post here ever again. I will solve things for myself and won't care about distro that doesn't care about feedback.
