### ISSUE TITLE
App Store not working in porteux 0.3

### ISSUE THREAD

**Issue by CemHyur** [porteux/porteux#8]
Hi...
Thank You for releasing porteux 0.3
strange that why every new release increasing in size from 0.1 to 0.3 (395mb to 409mb) (lxde Desktop)

secondly in app store following tried and getting Error:
Palemoon, Chrome Browser : get success message that (module added in /porteux/module folder), but nothing added
Nvidia5xx, Devel Kit, Crippled Source, wine : getting error (Error creating module)
Notepad++ : getting error (gtkdialog.py [-h] [-p PRIMARY_TEXT] [-d SECONDARY_TEXT] [-d DIALOG_TYPE] [-t TIMEOUT])

Used : porteux 0.3 lxde

**Comment by porteux** [comment]
@CemHyur, the ISOs got a bit bigger mainly because the kernel is now being compiled with aggressive compiling flags. It's a trade-off between disk space and performance. But it's also a work in progress, so it might change in the future. :)

I can't replicate your app store issues. I tested in LXDE normal boot and always fresh (which I recommend in your case). In both cases I tested NotepadNext, Devel, Crippled and Chrome, and they all downloaded, got copied to /porteux/modules and got activated (when the checkbox is checked). You should try always fresh boot mode and call the app store from the terminal to see the whole output: `/opt/porteux-scripts/porteux-app-store/porteux-app-store-live.sh`

**Comment by porteux** [comment]
Is it working? Can we close this ticket?

**Comment by CemHyur** [comment]
Yes working all like charm... : )
Problem was Internet connection was lost in host PC, It is working now.

Thanks.
